# Day 1

## Create and print an array of range 20 and also show its type

In [31]:
import numpy as np  # Using this command, we can call numpy using 'np' only
array = np.arange(20)   # Crates and array of range 20
print(type(array))  # Prints the type of the array
print(array)    # Print the contents of the array

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Print the range of the array and also print the data type of the range

In [32]:
print(array.shape)  # Print the length of the array
print(type(array.shape))    # Print the data type of the length of the array

(20,)
<class 'tuple'>


## Print the element present at the index number 3 of the array

In [33]:
array[3]    # Print the value of the element present in the 3rd index of the array

3

## Change the value of an element at a specific index

In [34]:
array[3] = 100  # Replace the value of the element present in the 3rd index with '100'
print(array)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


## Reshape the array into different parts of fixed length, creating a 2D array

In [35]:
x = array.reshape(4,5)  # Divide the array into 4 parts, with each part containing 5 elements. Store the final array into the variable x
print(x)

[[  0   1   2 100   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


## Create arrays from a starting element to an ending element with a set interval value

In [36]:
np.arange(0, 10)    # Print and array from 0 to 10 with no interval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(10,35,3)  # Print and array from 0 to 10 selecting only the 3rd element

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

## Create a 2D array of same numbers

In [38]:
np.zeros((2,4)) # Create an array of 2 rows and 4 columns with all elements as 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((3,4))  # Create an array of 3 rows and 4 columns with all elements as 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.full((3,4), 5)  # Create an array of 3 rows and 4 columns with all elements as 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## Create a 2D array of different numbers

In [41]:
np.eye(3,5)  # Create an array of 3 rows and 3 columns with the diagonal elements as 1 and the rest as 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [42]:
np.random.random((3,5))  # Create an array of 3 rows and 5 columns with random values

array([[0.38529891, 0.91936673, 0.73547569, 0.5716873 , 0.06196147],
       [0.01362028, 0.10760494, 0.49644533, 0.80676911, 0.54803704],
       [0.13394706, 0.24085252, 0.56194208, 0.55726881, 0.80146213]])

## Convert a list into an array and split into different arrays

In [43]:
my_list = np.arange(1,9)  # Create an array of 1 to 8
my_array = np.array(my_list)  # Convert the list into an array
print(my_array)
print(type(my_array))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [44]:
my_array = my_array.reshape(2,4)  # Reshape the array into 2 rows and 4 columns
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


## Perform operations on arrays

In [45]:
x = np.arange(1,4)  # Create an array of 1 to 3
y = np.arange(1,7,2)  # Create an array of 1 to 6 with an interval of 2
print(x)
print(y)
np.add(x,y)  # Add the two arrays and store the result in the variable x

# We can add arrays of same length only

[1 2 3]
[1 3 5]


array([2, 5, 8])

In [46]:
num = np.arange(1,10,dtype = float).reshape(3,3)  # Create an array from 1 to 9 of float data-type  and reshape into 3 rows and 3 columns
print(num)
print(np.max(num))  # Print the maximum value of the array
print(np.max(num, axis = 0))  # Print the maximum value of each row
print(np.max(num, axis = 1))  # Print the maximum value of each column

print(np.min(num))  # Print the minimum value of the array
print(np.sum(num))  # Print the sum of the array
print(np.mean(num))  # Print the mean of the array
print(np.std(num))  # Print the standard deviation of the array
print(np.var(num))  # Print the variance of the array

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
9.0
[7. 8. 9.]
[3. 6. 9.]
1.0
45.0
5.0
2.581988897471611
6.666666666666667


In [47]:
num[1,2] = np.NaN # Replace the value of the element present in the 2nd row and 3rd column with NaN
print(num)
np.max(num, axis=0)  # Print the maximum value of each row

[[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]]


array([ 7.,  8., nan])